### ISSUE TITLE
为啥点击搜索框，动画进行到2/3的位置时候会卡一下？

### ISSUE THREAD

**Issue by gincoo** [wenwenwen888/DouBan_Movie#1]
为啥点击Title搜索按钮，动画进行到2/3的位置时候会卡顿一下？不是很懂，求教教？要后退再点击，反复几次，偶尔会出现

**Comment by wenwenwen888** [comment]
@gincoo 手机硬件问题吧 , 我这边用模拟器跟手机都感觉不到 . 你的是什么机型

**Comment by gincoo** [comment]
huaweip9

**Comment by wenwenwen888** [comment]
@gincoo 我这里测试点击的时候是没有问题的 . 你有兴趣可以看看搜索框的源码https://github.com/wenwenwen888/SearchDialog
谢谢反馈 .
